### ISSUE TITLE
Add the missing deleteTag func in lib/data/repos/task_repo_impl.dart

### ISSUE THREAD

**Issue by HasanAlqaisi** [softshapeorg/diana-mobile#6]

**Comment by AliAkberAakash** [comment]
Hi, I'd like to be assigned this issue.

**Comment by HasanAlqaisi** [comment]
> Hi, I'd like to be assigned to this issue.

Hi!

I've assigned this issue to you, feel free to start contributing and thank you.

**Comment by AliAkberAakash** [comment]
Hi, I've cloned the project and I'm trying to run it, but there are many variables that are missing. I have added the _constants.dart file but still many variables such as kRefreshToken, kToken, kUserId, refreshKey, tokenKey etc are missing. are they sypposed to be in the _constant.dart file? The CONTRIBUTE.md file doesn't say anything about these.

**Comment by HasanAlqaisi** [comment]
> Hi, I've cloned the project and I'm trying to run it, but there are many variables that are missing. I have added the _constants.dart file but still many variables such as kRefreshToken, kToken, kUserId, refreshKey, tokenKey etc are missing. are they sypposed to be in the _constant.dart file? The CONTRIBUTE.md file doesn't say anything about these.

Sorry about that, the project under developing and I forgot to update CONTRIBUTE.md

Check it now please.

**Comment by AliAkberAakash** [comment]
Thanks, but I'm also getting some error for some generated classes, which are not generated in my machine. this is one of them "part 'app_database.g.dart';" I suppose I need to run some command to generate them?

**Comment by HasanAlqaisi** [comment]
> Thanks, but I'm also getting some error for some generated classes, which are not generated in my machine. this is one of them "part 'app_database.g.dart';" I suppose I need to run some command to generate them?

Oh, yeah you need to run (flutter pub run build_runner build) to get auto generated files.

I thought I added this to CONTRIBUTE.md before but obviously I am mistaken 😲

**Comment by AliAkberAakash** [comment]
Hi, I was able to resolve the errors and run the app, now I'm missing the following values
`const baseUrl = 'WRITE_BASE_URL_VALUE';
const refreshKey = 'REFRESH_KEY';
const tokenKey = 'TOKEN_KEY';
const userIdKey = 'USER_ID_KEY';`
Where am I supposed to get them from?

**Comment by HasanAlqaisi** [comment]
> Hi, I was able to resolve the errors and run the app, now I'm missing the following values
> `const baseUrl = 'WRITE_BASE_URL_VALUE'; const refreshKey = 'REFRESH_KEY'; const tokenKey = 'TOKEN_KEY'; const userIdKey = 'USER_ID_KEY';`
> Where am I supposed to get them from?

Hi, I updated CONTRIBUTE.md with the baseUrl, and the other fields they are just keys to access the storage so you can leave it like it is

I added the link of the API DOC in the other link section as well

**Comment by AliAkberAakash** [comment]
I've submitted a pull request for this issue #7

**Comment by HasanAlqaisi** [comment]
Merge done, thank you Ali for your contributing! 👍🏻
